In [3]:
# !pip install joblib

In [4]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [16]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
    
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X_with_bias: \n{X_with_bias}")
        

In [17]:
obj = Perceptron(eta=0.01, epochs=10)

In [18]:
obj.eta

0.01

In [19]:
obj.epochs

10

In [20]:
obj.weights

array([1.20457394e-04, 3.78237728e-05, 1.46136038e-04])

In [22]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [24]:
obj.fit(X, y)

X_with_bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
